// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQc5RyAO_5J0lROOLPOKENPAFZU74kwQQ',
    appId: '1:465689120671:web:15d3df0041dea0134db7aa',
    messagingSenderId: '465689120671',
    projectId: 'mega-mart-289da',
    authDomain: 'mega-mart-289da.firebaseapp.com',
    storageBucket: 'mega-mart-289da.firebasestorage.app',
    measurementId: 'G-GCGZHW4FVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQBUjIAj0B57WgojqKgTqSMXwZvBk6fkM',
    appId: '1:465689120671:android:ffa1255f34e731e34db7aa',
    messagingSenderId: '465689120671',
    projectId: 'mega-mart-289da',
    storageBucket: 'mega-mart-289da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXsbu2UlJrEx-3FhfLGA2vV8B9IRa5MOQ',
    appId: '1:465689120671:ios:a1a4f6682c75d6194db7aa',
    messagingSenderId: '465689120671',
    projectId: 'mega-mart-289da',
    storageBucket: 'mega-mart-289da.firebasestorage.app',
    iosBundleId: 'com.example.mega',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXsbu2UlJrEx-3FhfLGA2vV8B9IRa5MOQ',
    appId: '1:465689120671:ios:a1a4f6682c75d6194db7aa',
    messagingSenderId: '465689120671',
    projectId: 'mega-mart-289da',
    storageBucket: 'mega-mart-289da.firebasestorage.app',
    iosBundleId: 'com.example.mega',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQc5RyAO_5J0lROOLPOKENPAFZU74kwQQ',
    appId: '1:465689120671:web:0d59d26d80d06b3b4db7aa',
    messagingSenderId: '465689120671',
    projectId: 'mega-mart-289da',
    authDomain: 'mega-mart-289da.firebaseapp.com',
    storageBucket: 'mega-mart-289da.firebasestorage.app',
    measurementId: 'G-WNV1CSN7HH',
  );
}